-- 오프라인/온라인 판매 데이터 통합하기 LV4
SELECT  TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
  FROM ONLINE_SALE 
WHERE TRUNC(SALES_DATE, 'MM') = TO_DATE('2022-03', 'YYYY-MM')
 UNION 
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
 FROM OFFLINE_SALE  
WHERE TRUNC(SALES_DATE, 'MM') = TO_DATE('2022-03', 'YYYY-MM')
ORDER BY SALES_DATE ASC;


