-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH, 
       GENDER, 
       COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO 
        JOIN 
    ONLINE_SALE 
USING (USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE), 
         EXTRACT(MONTH FROM SALES_DATE), 
         GENDER
ORDER BY EXTRACT(YEAR FROM SALES_DATE), 
         EXTRACT(MONTH FROM SALES_DATE), 
         GENDER;



