-- 5월 식품들의 총매출 조회하기(LEVEL4) : 230322
WITH ORDERS AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-mm') = '2022-05'
    GROUP BY PRODUCT_ID
    ORDER BY PRODUCT_ID
), 
PRODUCTS AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
    FROM FOOD_PRODUCT
)
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM PRODUCTS JOIN ORDERS
USING (PRODUCT_ID)
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
