-- 코드를 입력하세요
-- PRICE * SALES AS TOTAL_SALES
WITH TMP AS (
    SELECT BOOK_ID, CATEGORY, AUTHOR_ID, PRICE
    FROM BOOK
        JOIN
        (SELECT AUTHOR_ID, CATEGORY
        FROM BOOK
        GROUP BY AUTHOR_ID, CATEGORY)
    USING (AUTHOR_ID, CATEGORY)
    ORDER BY AUTHOR_ID, CATEGORY DESC
),
SALES AS (
    SELECT *
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
),
TMP1 AS (
SELECT *
FROM TMP T JOIN SALES S
USING (BOOK_ID))
SELECT AUTHOR_ID,AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM (
    SELECT AUTHOR_ID, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
    FROM TMP1 
    GROUP BY AUTHOR_ID, CATEGORY
) JOIN AUTHOR
USING(AUTHOR_ID)
ORDER BY AUTHOR_ID, CATEGORY DESC



