-- 24/12/12 조건에 부합하는 중고거래 댓글 조회하기
-- 게시글 기준 2022년 10월 작성
WITH COMMENTS AS (
SELECT 
    GB.TITLE, 
    GB.BOARD_ID, 
    GR.REPLY_ID, 
    GR.WRITER_ID, 
    GR.CONTENTS, 
    TO_CHAR(GR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM (
        SELECT *
        FROM USED_GOODS_BOARD
        WHERE TO_CHAR(CREATED_DATE, 'YYYY-MM') = '2022-10'
        ) GB 
        JOIN 
    USED_GOODS_REPLY GR
ON GB.BOARD_ID = GR.BOARD_ID
ORDER BY GR.CREATED_DATE ASC, GB.TITLE ASC
)

SELECT *
FROM COMMENTS
