-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE FP.PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY = FP.CATEGORY
      AND CATEGORY IN ('과자', '국', '김치', '식용유')
)
ORDER BY FP.PRICE DESC
