-- 조건에 맞는 도서와 저자 리스트 출력하기 `240521
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-dd') AS "PUBLISHED_DATE"
FROM (
    SELECT *
    FROM AUTHOR JOIN (
    SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
        FROM BOOK
    WHERE CATEGORY = '경제')
    USING (AUTHOR_ID)
)
ORDER BY PUBLISHED_DATE
